upstream_package_name: daemon
downstream_package_name: daemon
specfile_path: daemon.spec

srpm_build_deps:
  - tito
  - gcc
  - git-core
  - make
  - rpm-build
  - 'pkgconfig(systemd)'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9